// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { SupabaseClient as SupabaseClientType } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL =
  import.meta.env.VITE_SUPABASE_URL ??
  import.meta.env.VITE_SUPABASE_PROJECT_URL ??
  '';
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ??
  import.meta.env.VITE_SUPABASE_ANON_KEY ??
  '';

// Lazy / browser-only initialization to avoid "supabaseUrl is required" during build/SSR
let _supabase: SupabaseClientType | null = null;

if (typeof window !== 'undefined') {
  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    // Fail gracefully in the client and provide actionable message in console.
    // If you see this in production, make sure the variables are set in your hosting dashboard:
    // VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY (or VITE_SUPABASE_ANON_KEY)
    // Example (Vercel/Netlify): add them as build & runtime env vars and re-deploy.
    // This prevents the app from throwing during module initialization and producing a blank screen.
    console.error(
      'Supabase not initialized: set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY (or VITE_SUPABASE_ANON_KEY) as build-time env vars.'
    );
  } else {
    _supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      },
    });
  }
}

export const supabase = _supabase;
