// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { SupabaseClient as SupabaseClientType } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL =
  import.meta.env.VITE_SUPABASE_URL ??
  import.meta.env.VITE_SUPABASE_PROJECT_URL ??
  '';
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ??
  import.meta.env.VITE_SUPABASE_ANON_KEY ??
  '';

// Lazy / browser-only initialization to avoid "supabaseUrl is required" during build/SSR
let _supabase: SupabaseClientType | null = null;

if (typeof window !== 'undefined') {
  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    // Fail gracefully in the client and provide actionable message in console.
    // If you see this in production, make sure the variables are set in your hosting dashboard:
    // VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY (or VITE_SUPABASE_ANON_KEY)
    // Example (Vercel/Netlify): add them as build & runtime env vars and re-deploy.
    // This prevents the app from throwing during module initialization and producing a blank screen.
    console.error(
      'Supabase not initialized: set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY (or VITE_SUPABASE_ANON_KEY) as build-time env vars.'
    );
  } else {
    _supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      },
    });
  }
}

// Export a safe client: if not configured, throw helpful error on first use instead of crashing with "cannot read property of null"
export const supabase: SupabaseClientType = (_supabase ||
  (new Proxy({} as SupabaseClientType, {
    get(_target, prop) {
      const hint =
        'Supabase is not configured. Set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY (or VITE_SUPABASE_ANON_KEY) in your hosting dashboard and redeploy.';
      // Keep console error for visibility in production logs
      if (typeof window !== 'undefined') {
        // eslint-disable-next-line no-console
        console.error(hint);
      }
      throw new Error(hint + ` Attempted to access client property "${String(prop)}".`);
    },
  })) as SupabaseClientType);
